version: '3'
services:

  elasticsearch:
    image: "elasticsearch:5"
    restart: always
    volumes:
      - ./ES_DATA:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  redis-1:
    image: redis:3.2
    ports:
      - "6379:6379"

  redis-2:
    image: redis:3.2
    ports:
      - "6380:6379"

  redis-3:
    image: redis:3.2
    ports:
      - "6381:6379"
